-- MySQL Script generated by MySQL Workbench
-- Wed Dec 12 23:42:23 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema escolacenso
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema escolacenso
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escolacenso` DEFAULT CHARACTER SET utf8 ;
USE `escolacenso` ;

-- -----------------------------------------------------
-- Table `escolacenso`.`RACA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escolacenso`.`RACA` (
  `ID` INT NOT NULL,
  `TP_RACA` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escolacenso`.`SEXO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escolacenso`.`SEXO` (
  `ID` INT NOT NULL,
  `TP_SEXO` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escolacenso`.`LOCALIZACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escolacenso`.`LOCALIZACAO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `COD_REGIAO` VARCHAR(45) NULL,
  `COD_UF` VARCHAR(45) NULL,
  `TP_LOCALIZACAO` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escolacenso`.`ESGOTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escolacenso`.`ESGOTO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ESGOTO_REDE_PUBLICA` INT NULL,
  `ESGOTO_FOSSA` INT NULL,
  `ESGOTO_INEXISTENTE` INT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escolacenso`.`ENERGIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escolacenso`.`ENERGIA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ENERGIA_REDE_PUBLICA` INT NULL,
  `ENERGIA_GERADOR` INT NULL,
  `ENERGIA_OUTROS` INT NULL,
  `ENERGIA_INEXISTENTE` INT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escolacenso`.`AGUA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escolacenso`.`AGUA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `AGUA_FILTRADA` INT NULL,
  `AGUA_REDE_PUBLICA` INT NULL,
  `AGUA_POCO_ARTESIANO` INT NULL,
  `AGUA_CACIMBA` INT NULL,
  `AGUA_FONTE_RIO` INT NULL,
  `AGUA_INEXISTENTE` INT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escolacenso`.`ACESSIBILIDADE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escolacenso`.`ACESSIBILIDADE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `BANHEIRO_PNE` INT NULL,
  `DEPENDENCIAS_PNE` INT NULL,
  `SALA_ATENDIMENTO_ESPECIAL` INT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escolacenso`.`INFRAESTRUTURA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escolacenso`.`INFRAESTRUTURA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ESGOTO_ID` INT NOT NULL,
  `ENERGIA_ID` INT NOT NULL,
  `AGUA_ID` INT NOT NULL,
  `ACESSIBILIDADE_ID` INT NOT NULL,
  `BIBLIOTECA` INT NULL,
  `AUDITORIO` INT NULL,
  `NUM_SALAS_EXISTENTES` INT NULL,
  `NUM_SALAS_UTILIZADAS` INT NULL,
  `NUM_COMPUTADOR` INT NULL,
  `NUM_COMP_ADMINISTRATIVO` INT NULL,
  `NUM_COMP_ALUNO` INT NULL,
  `IN_INTERNET` INT NULL,
  `ALIMENTACAO` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_INFRAESTRUTURA_ESGOTO1_idx` (`ESGOTO_ID` ASC),
  INDEX `fk_INFRAESTRUTURA_ENERGIA1_idx` (`ENERGIA_ID` ASC),
  INDEX `fk_INFRAESTRUTURA_AGUA1_idx` (`AGUA_ID` ASC),
  INDEX `fk_INFRAESTRUTURA_ACESSIBILIDADE1_idx` (`ACESSIBILIDADE_ID` ASC),
  CONSTRAINT `fk_INFRAESTRUTURA_ESGOTO1`
    FOREIGN KEY (`ESGOTO_ID`)
    REFERENCES `escolacenso`.`ESGOTO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_INFRAESTRUTURA_ENERGIA1`
    FOREIGN KEY (`ENERGIA_ID`)
    REFERENCES `escolacenso`.`ENERGIA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_INFRAESTRUTURA_AGUA1`
    FOREIGN KEY (`AGUA_ID`)
    REFERENCES `escolacenso`.`AGUA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_INFRAESTRUTURA_ACESSIBILIDADE1`
    FOREIGN KEY (`ACESSIBILIDADE_ID`)
    REFERENCES `escolacenso`.`ACESSIBILIDADE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escolacenso`.`ESCOLA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escolacenso`.`ESCOLA` (
  `COD_ESCOLA` BIGINT NOT NULL,
  `NOME` VARCHAR(100) NULL,
  `TP_SITUACAO_FUNCIONAMENTO` INT NULL,
  `REGULAMENTACAO` INT NULL,
  `TP_DEPENDENCIA` INT NULL,
  `INFRAESTRUTURA_ID` INT NOT NULL,
  `LOCALIZACAO_ID` INT NOT NULL,
  PRIMARY KEY (`COD_ESCOLA`),
  INDEX `fk_ESCOLA_INFRAESTRUTURA1_idx` (`INFRAESTRUTURA_ID` ASC),
  INDEX `fk_ESCOLA_LOCALIZACAO1_idx` (`LOCALIZACAO_ID` ASC),
  CONSTRAINT `fk_ESCOLA_INFRAESTRUTURA1`
    FOREIGN KEY (`INFRAESTRUTURA_ID`)
    REFERENCES `escolacenso`.`INFRAESTRUTURA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ESCOLA_LOCALIZACAO1`
    FOREIGN KEY (`LOCALIZACAO_ID`)
    REFERENCES `escolacenso`.`LOCALIZACAO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escolacenso`.`ALUNO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escolacenso`.`ALUNO` (
  `ID_PESSOA_FISICA` BIGINT NOT NULL,
  `MATRICULA_ID` INT NOT NULL,
  `RACA_ID` INT NOT NULL,
  `SEXO_ID` INT NOT NULL,
  `LOCALIZACAO_ID` INT NOT NULL,
  `ESCOLA_COD_ESCOLA` BIGINT NOT NULL,
  `IDADE` INT NULL,
  PRIMARY KEY (`ID_PESSOA_FISICA`, `MATRICULA_ID`),
  INDEX `fk_ALUNO_RACA1_idx` (`RACA_ID` ASC),
  INDEX `fk_ALUNO_SEXO1_idx` (`SEXO_ID` ASC),
  INDEX `fk_ALUNO_LOCALIZACAO1_idx` (`LOCALIZACAO_ID` ASC),
  INDEX `fk_ALUNO_ESCOLA1_idx` (`ESCOLA_COD_ESCOLA` ASC),
  CONSTRAINT `fk_ALUNO_RACA1`
    FOREIGN KEY (`RACA_ID`)
    REFERENCES `escolacenso`.`RACA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ALUNO_SEXO1`
    FOREIGN KEY (`SEXO_ID`)
    REFERENCES `escolacenso`.`SEXO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ALUNO_LOCALIZACAO1`
    FOREIGN KEY (`LOCALIZACAO_ID`)
    REFERENCES `escolacenso`.`LOCALIZACAO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ALUNO_ESCOLA1`
    FOREIGN KEY (`ESCOLA_COD_ESCOLA`)
    REFERENCES `escolacenso`.`ESCOLA` (`COD_ESCOLA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escolacenso`.`NECESSIDADE_ESPECIAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escolacenso`.`NECESSIDADE_ESPECIAL` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TP_NECESSIDADE` VARCHAR(100) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escolacenso`.`ALUNO_has_NECESSIDADE_ESPECIAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escolacenso`.`ALUNO_has_NECESSIDADE_ESPECIAL` (
  `NECESSIDADE_ESPECIAL_ID` INT NOT NULL,
  `ALUNO_ID_PESSOA_FISICA` BIGINT NOT NULL,
  `ALUNO_MATRICULA_ID` INT NOT NULL,
  PRIMARY KEY (`NECESSIDADE_ESPECIAL_ID`, `ALUNO_ID_PESSOA_FISICA`, `ALUNO_MATRICULA_ID`),
  INDEX `fk_ALUNO_has_NECESSIDADE_ESPECIAL_NECESSIDADE_ESPECIAL1_idx` (`NECESSIDADE_ESPECIAL_ID` ASC),
  INDEX `fk_ALUNO_has_NECESSIDADE_ESPECIAL_ALUNO1_idx` (`ALUNO_ID_PESSOA_FISICA` ASC, `ALUNO_MATRICULA_ID` ASC),
  CONSTRAINT `fk_ALUNO_has_NECESSIDADE_ESPECIAL_NECESSIDADE_ESPECIAL1`
    FOREIGN KEY (`NECESSIDADE_ESPECIAL_ID`)
    REFERENCES `escolacenso`.`NECESSIDADE_ESPECIAL` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ALUNO_has_NECESSIDADE_ESPECIAL_ALUNO1`
    FOREIGN KEY (`ALUNO_ID_PESSOA_FISICA` , `ALUNO_MATRICULA_ID`)
    REFERENCES `escolacenso`.`ALUNO` (`ID_PESSOA_FISICA` , `MATRICULA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
